/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xN39iLpHxKD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Orbit } from "lucide-react"
import { MountainIcon } from "lucide-react"

export default function resetPassword() {
  return (
    (<div
    className="flex min-h-screen flex-col items-center justify-center bg-background bg-[url('/globe.webp')] bg-cover bg-center brightness-75 px-4 py-12 sm:px-6 lg:px-8"
    >
      <div className="w-full max-w-md space-y-8">
        <div>
          <MountainIcon className="mx-auto h-20 w-20"></MountainIcon>
          <h2
            className="mt-6 text-center text-3xl font-bold tracking-tight text-foreground">Reset Your Password</h2>
          <p className="mt-2 text-center text-sm text-muted-foreground">
            Enter your new password below to reset your account.
          </p>
        </div>
        <div className="space-y-6">
          <form className="space-y-4" onSubmit={(e) => e.preventDefault()}>
            <div>
              <Label htmlFor="password">New Password</Label>
              <Input
                id="password"
                type="password"
                autoComplete="new-password"
                required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary focus:ring-primary" />
            </div>
            <div>
              <Label htmlFor="verifyPassword">Verify Password</Label>
              <Input
                id="verifyPassword"
                type="password"
                autoComplete="new-password"
                required
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary focus:ring-primary" />
            </div>
            <Button type="submit" className="w-full">
              Reset Password
            </Button>
          </form>
        </div>
      </div>
    </div>)
  );
}
