/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/07A7fM8Q2zu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { NavigationMenu, NavigationMenuList, NavigationMenuLink } from "@/components/ui/navigation-menu"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

export function AdminDashboard() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-40 border-b bg-background">
        <div className="container flex h-16 items-center justify-between px-4 sm:px-6 md:px-8">
          <nav className="flex items-center gap-4 md:gap-6">
            <Link href="#" className="flex items-center gap-2 font-bold" prefetch={false}>
              <OrbitIcon className="h-6 w-6" />
              <span className="sr-only">Astrologer Dashboard</span>
            </Link>
            <NavigationMenu>
              <NavigationMenuList>
                <NavigationMenuLink asChild>
                  <Link href="#" className="px-4 py-2 text-sm font-medium" prefetch={false}>
                    My Profile
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link href="#" className="px-4 py-2 text-sm font-medium" prefetch={false}>
                    Plans and Settings
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link href="#" className="px-4 py-2 text-sm font-medium" prefetch={false}>
                    Users
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link href="#" className="px-4 py-2 text-sm font-medium" prefetch={false}>
                    Price Plans
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link href="#" className="px-4 py-2 text-sm font-medium" prefetch={false}>
                    Logout
                  </Link>
                </NavigationMenuLink>
              </NavigationMenuList>
            </NavigationMenu>
          </nav>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
                <img
                  src="/placeholder.svg"
                  width={36}
                  height={36}
                  alt="Avatar"
                  className="overflow-hidden rounded-full"
                  style={{ aspectRatio: "36/36", objectFit: "cover" }}
                />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 container px-4 py-8 sm:px-6 md:px-8">
        <Tabs defaultValue="queries">
          <TabsList>
            <TabsTrigger value="queries">User Queries</TabsTrigger>
            <TabsTrigger value="analytics">User Analytics</TabsTrigger>
            <TabsTrigger value="chat">Live Chat</TabsTrigger>
            <TabsTrigger value="price-plans">Price Plans</TabsTrigger>
            <TabsTrigger value="users">Users</TabsTrigger>
          </TabsList>
          <TabsContent value="queries">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>User Queries</CardTitle>
                  <CardDescription>View, reply, and remove user queries.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>User</TableHead>
                        <TableHead>Query</TableHead>
                        <TableHead>Date</TableHead>
                        <TableHead>Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>
                          <div className="flex items-center gap-3">
                            <Avatar>
                              <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                              <AvatarFallback>JD</AvatarFallback>
                            </Avatar>
                            <div>
                              <div className="font-medium">John Doe</div>
                              <div className="text-sm text-muted-foreground">johndoe@example.com</div>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div>
                            <div className="font-medium">Astrology Consultation</div>
                            <div className="text-sm text-muted-foreground">
                              I would like to schedule an astrology consultation.
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm text-muted-foreground">2023-04-15</div>
                        </TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button size="icon" variant="ghost">
                                <MoveVerticalIcon className="h-5 w-5" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem>
                                <UserIcon className="mr-2 h-4 w-4" />
                                View Profile
                              </DropdownMenuItem>
                              <DropdownMenuItem>
                                <MessageCircleIcon className="mr-2 h-4 w-4" />
                                Reply
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem className="text-red-500">
                                <TrashIcon className="mr-2 h-4 w-4" />
                                Remove
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="analytics">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>User Analytics</CardTitle>
                  <CardDescription>Overview of your user base.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">1,234</CardTitle>
                        <CardDescription>Total Registered Users</CardDescription>
                      </CardHeader>
                    </Card>
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">789</CardTitle>
                        <CardDescription>Total Subscribed Users</CardDescription>
                      </CardHeader>
                    </Card>
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">456</CardTitle>
                        <CardDescription>Users with Active Plans</CardDescription>
                      </CardHeader>
                    </Card>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="chat">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Live Chat</CardTitle>
                  <CardDescription>Respond to user queries in real-time.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col gap-4">
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div className="flex-1 rounded-lg bg-muted p-4">
                        <div className="flex items-center justify-between">
                          <div className="font-medium">John Doe</div>
                          <div className="text-xs text-muted-foreground">2:39 PM</div>
                        </div>
                        <div>
                          <p>Hi, I'm interested in getting an astrology reading. Can you help me with that?</p>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div className="flex-1 rounded-lg bg-muted p-4">
                        <div className="flex items-center justify-between">
                          <div className="font-medium">Jane Smith</div>
                          <div className="text-xs text-muted-foreground">2:41 PM</div>
                        </div>
                        <div>
                          <p>I'm having trouble understanding my birth chart. Can you explain it to me?</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <form className="flex gap-2">
                    <Input type="text" placeholder="Type your message..." className="flex-1" />
                    <Button type="submit">Send</Button>
                  </form>
                </CardFooter>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="price-plans">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Price Plans</CardTitle>
                  <CardDescription>Manage your price plans.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">Basic</CardTitle>
                        <CardDescription>$9.99/month</CardDescription>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2 text-sm">
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            10 Astrology Consultations
                          </li>
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Basic Birth Chart Analysis
                          </li>
                          <li>
                            <XIcon className="mr-2 h-4 w-4 text-red-500" />
                            No Priority Support
                          </li>
                        </ul>
                      </CardContent>
                      <CardFooter>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="secondary">
                          Delete
                        </Button>
                      </CardFooter>
                    </Card>
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">Premium</CardTitle>
                        <CardDescription>$19.99/month</CardDescription>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2 text-sm">
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Unlimited Astrology Consultations
                          </li>
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Advanced Birth Chart Analysis
                          </li>
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Priority Support
                          </li>
                        </ul>
                      </CardContent>
                      <CardFooter>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="secondary">
                          Delete
                        </Button>
                      </CardFooter>
                    </Card>
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">Enterprise</CardTitle>
                        <CardDescription>$49.99/month</CardDescription>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2 text-sm">
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Unlimited Astrology Consultations
                          </li>
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Advanced Birth Chart Analysis
                          </li>
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Priority Support
                          </li>
                          <li>
                            <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
                            Dedicated Account Manager
                          </li>
                        </ul>
                      </CardContent>
                      <CardFooter>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="secondary">
                          Delete
                        </Button>
                      </CardFooter>
                    </Card>
                    <Card>
                      <CardHeader className="pb-2">
                        <CardTitle className="text-2xl font-bold">Add New Plan</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <form className="grid gap-4">
                          <div className="grid gap-2">
                            <Label htmlFor="plan-name">Plan Name</Label>
                            <Input id="plan-name" type="text" />
                          </div>
                          <div className="grid gap-2">
                            <Label htmlFor="plan-price">Price</Label>
                            <Input id="plan-price" type="number" />
                          </div>
                          <div className="grid gap-2">
                            <Label htmlFor="plan-features">Features</Label>
                            <Textarea id="plan-features" rows={3} />
                          </div>
                        </form>
                      </CardContent>
                      <CardFooter>
                        <Button size="sm">Save</Button>
                      </CardFooter>
                    </Card>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="users">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Users</CardTitle>
                  <CardDescription>Manage your users.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table />
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </main>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function MessageCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function MoveVerticalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="8 18 12 22 16 18" />
      <polyline points="8 6 12 2 16 6" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>
  )
}


function OrbitIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="3" />
      <circle cx="19" cy="5" r="2" />
      <circle cx="5" cy="19" r="2" />
      <path d="M10.4 21.9a10 10 0 0 0 9.941-15.416" />
      <path d="M13.5 2.1a10 10 0 0 0-9.841 15.416" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
